baseURL: "https://aldric-l.github.io/" 
title: Aldric Labarthe
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1
        - name: Courses
          url: courses/
          weight: 3
        - name: Past Courses
          url: previouscourses/
          weight: 4
        - name: Miscellaneous projects
          url: projects/
          weight: 5

params:
    # SEO Description (Optimized for Google search snippets)
    description: "Program coordinator at ENSAE Paris & Researcher in applied mathematics at ENS Paris-Saclay. Interest in computational medicine, economic equilibrium, and graph geometry."
    author: Aldric Labarthe
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    ShowCodeCopyButtons: true
    MainSections: ["research", "projects", "previouscourses"]
    math: true # Crucial for your LaTeX rendering

    profileMode:
          enabled: true
          title: Aldric Labarthe
          # Full academic description for the homepage
          subtitle: "Graduate program teaching coordinator in statistics and machine learning at ENSAE Paris & Ph.D. candidate in applied mathematics from the École Normale Supérieure Paris-Saclay."
          imageUrl: "PDP.jpg"
          imageWidth: 185
          imageHeight: 185
          buttons:
            - name: Courses
              url: courses/
            - name: Past Courses
              url: previouscourses/
            - name: Office
              url: officehours/
          
          # Custom fields you added to your template
          researchtext: "I am currently pursuing research in 3 main directions:"
          researchbuttons:
            - name: Graphs and Geometry
              url: research/graphs/
            - name: Mathematical economics
              url: research/mathematical-economics/
            - name: Medical Imaging
              url: research/medical-imaging/

    socialIcons:
        - name: CV
          url: ALabarthe_AcademicCV2026.pdf
        - name: Email
          url: mailto:aldric.labarthe@ens-paris-saclay.fr # Real email for browser functionality
        - name: Google Scholar
          url: https://scholar.google.fr/citations?user=n2arORsAAAAJ&hl=fr
        - name: GitHub
          url: https://github.com/Aldric-L
        - name: YouTube
          url: https://www.youtube.com/@AldricLabarthe

    label:
      text: "Aldric Labarthe"
      icon: PDP.jpg # This shows a tiny version of your photo next to your name in the nav
      iconHeight: 18
    env: "production"

markup:
    goldmark:
        renderer:
            unsafe: true # Allows your custom HTML/SVG icons in Markdown
    highlight:
        guessSyntax: true
        style: autumn